// <auto-generated />
using System;
using IncomeCalculator.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IncomeCalculator.Migrations
{
    [DbContext(typeof(BenefitsContext))]
    [Migration("20211126120205_Empty")]
    partial class Empty
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("Latin1_General_CI_AS")
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("IncomeCalculator.Data.ChildTaxCredit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<decimal>("ChildElement")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("FamilyElement")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("TaxYear")
                        .HasColumnType("date");

                    b.Property<decimal>("Threshold")
                        .HasColumnType("decimal(18,2)");

                    b.Property<float>("WithdrawalRate")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.ToTable("ChildTaxCredits");
                });

            modelBuilder.Entity("IncomeCalculator.Data.MinWage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<DateTime>("TaxYear")
                        .HasColumnType("date");

                    b.Property<decimal>("Wage")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("MinWages");
                });

            modelBuilder.Entity("IncomeCalculator.Data.WorkingTaxCredit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<decimal>("BasicElement")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SecondAdult")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("TaxYear")
                        .HasColumnType("date");

                    b.Property<decimal>("ThirtyHourElement")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Threshold")
                        .HasColumnType("decimal(18,2)");

                    b.Property<float>("WithdrawalRate")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.ToTable("WorkingTaxCredits");
                });
#pragma warning restore 612, 618
        }
    }
}
